# Builds and upload to Google Cloud Storage
name: upload-to-google-cloud-storage
run-name: ${{ github.actor }} build, version and deploy to Cloud storage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      # Get repo
      - uses: actions/checkout@v2
      # Use and setup Node and build
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Install depedencies
      - name: Install dependencies
        run: yarn install
      # Build
      - name: Build
        run: yarn build
      # Set GH Token for semantic release
      - name: Set token for semantic release
        run: export GH_TOKEN=${{ secrets.GH_TOKEN }}
      # Versioning
      - name: Versioning
        run: yarn semantic-release
      # - uses: google-github-actions/upload-cloud-storage@v1
